'use client'; import { useState, useEffect, useCallback } from 'react'; import { useRouter } from 'next/navigation'; import Link from 'next/link'; import { legalApi } from '@/lib/api';

const STATUS_COLORS: Record<string, string> = { active: 'bg-green-100 text-green-800', amended: 'bg-yellow-100 text-yellow-800', repealed: 'bg-red-100 text-red-800', superseded: 'bg-gray-100 text-gray-800' };
const CAT_COLORS: Record<string, string> = { safety: 'bg-red-100', health: 'bg-blue-100', environment: 'bg-green-100', quality: 'bg-yellow-100', security: 'bg-purple-100', labor: 'bg-indigo-100', industry: 'bg-teal-100' };

export default function RegulationsListPage() {
  const router = useRouter();
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title: '', description: '', regulationNumber: '', issuingBody: '', category: '', jurisdiction: '', status: 'active' });

  const fetchData = useCallback(async () => { setLoading(true); try { const r = await legalApi.getRegulations({ page, limit: 20 }); setItems(r.data.data||[]); setTotalPages(r.data.meta?.totalPages||1); } catch (e) { console.error(e); } finally { setLoading(false); } }, [page]);
  useEffect(() => { fetchData(); }, [fetchData]);

  const handleCreate = async () => { try { await legalApi.createRegulation(form); setShowForm(false); setForm({ title: '', description: '', regulationNumber: '', issuingBody: '', category: '', jurisdiction: '', status: 'active' }); fetchData(); } catch (e: any) { alert(e.response?.data?.message || 'Error'); } };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Regulations Register</h1><p className="text-gray-600 mt-1">Manage legal regulations and standards</p></div><button onClick={()=>setShowForm(!showForm)} className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm">+ New Regulation</button></div>

      {showForm&&(<div className="bg-white rounded-lg shadow p-6 space-y-4"><h3 className="font-semibold">New Regulation</h3><div className="grid gap-3 md:grid-cols-2"><input className="px-3 py-2 border rounded-lg text-sm" placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} /><input className="px-3 py-2 border rounded-lg text-sm" placeholder="Regulation Number" value={form.regulationNumber} onChange={e=>setForm({...form,regulationNumber:e.target.value})} /><input className="px-3 py-2 border rounded-lg text-sm" placeholder="Issuing Body" value={form.issuingBody} onChange={e=>setForm({...form,issuingBody:e.target.value})} /><select className="px-3 py-2 border rounded-lg text-sm" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Category</option><option value="safety">Safety</option><option value="health">Health</option><option value="environment">Environment</option><option value="quality">Quality</option><option value="security">Security</option><option value="labor">Labor</option><option value="industry">Industry</option></select><select className="px-3 py-2 border rounded-lg text-sm" value={form.jurisdiction} onChange={e=>setForm({...form,jurisdiction:e.target.value})}><option value="">Jurisdiction</option><option value="national">National</option><option value="provincial">Provincial</option><option value="local">Local</option><option value="international">International</option></select></div><textarea className="w-full px-3 py-2 border rounded-lg text-sm" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={2} /><div className="flex gap-2"><button onClick={handleCreate} className="px-4 py-2 bg-green-600 text-white rounded-lg text-sm">Save</button><button onClick={()=>setShowForm(false)} className="px-4 py-2 bg-gray-300 rounded-lg text-sm">Cancel</button></div></div>)}

      {loading?<div className="text-center py-12 text-gray-500">Loading...</div>:items.length===0?<div className="text-center py-12 bg-white rounded-lg shadow"><p className="text-gray-500">No regulations</p></div>:(
        <div className="bg-white rounded-lg shadow overflow-hidden"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Title</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Reg No</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Category</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Jurisdiction</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Obligations</th></tr></thead><tbody className="divide-y divide-gray-200">{items.map((r:any)=>(<tr key={r.id} className="hover:bg-gray-50 cursor-pointer" onClick={()=>router.push(`/dashboard/legal/regulations?id=${r.id}`)}><td className="px-4 py-3 text-sm font-medium text-blue-600 hover:underline">{r.title}</td><td className="px-4 py-3 text-sm text-gray-500 font-mono">{r.regulationNumber||'-'}</td><td className="px-4 py-3"><span className={`inline-flex px-2 py-0.5 rounded text-xs font-medium ${CAT_COLORS[r.category]||'bg-gray-100'}`}>{r.category||'-'}</span></td><td className="px-4 py-3 text-sm text-gray-500">{r.jurisdiction||'-'}</td><td className="px-4 py-3"><span className={`inline-flex px-2 py-0.5 rounded text-xs font-medium ${STATUS_COLORS[r.status]||'bg-gray-100'}`}>{r.status}</span></td><td className="px-4 py-3 text-sm text-gray-500">{r.obligations?.length||0}</td></tr>))}</tbody></table>
          {totalPages>1&&(<div className="flex items-center justify-between px-4 py-3 bg-gray-50 border-t"><div className="flex gap-2"><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} className="px-3 py-1 text-sm border rounded disabled:opacity-50">Prev</button><span className="text-sm">Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} className="px-3 py-1 text-sm border rounded disabled:opacity-50">Next</button></div></div>)}
        </div>
      )}
    </div>
  );
}
